### ISSUE TITLE
AssetValidatorCI.RunValidation isSuccessful inverted

### ISSUE THREAD

**Issue by tylorr** [jeffcampbellmakesgames/unity-asset-validator#1]
The check for if a run was successful is inverted. It's only going to be marked successful if any errors were logged.

**Comment by jeffcampbellmakesgames** [comment]
Roger that, thanks @tylorr. I should have some time in the next few days to take a look. Where was this check being performed exactly?

**Comment by tylorr** [comment]
Here: https://github.com/jeffcampbellmakesgames/unity-asset-validator/blob/1a747b6c659f4781adc2da80ac14cfdd82d97ea5/Editor/CI/AssetValidatorCI.cs#L181

**Comment by jeffcampbellmakesgames** [comment]
I apologize on the lateness of the response for this issue. There has been a great deal of life-changing circumstances that delayed any work on this tool for some time and that is something that is changing soon so that I can better develop and respond to issues regarding this tool.

I have fixed this issue in the latest release [here](https://github.com/jeffcampbellmakesgames/unity-asset-validator/releases/tag/v1.1.). Please let me know if this resolves this issue for you, otherwise I will close this issue in a week.
